# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowOpacity(0.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonCsv = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCsv.setGeometry(QtCore.QRect(660, 93, 111, 26))
        self.buttonCsv.setObjectName("buttonCsv")
        self.textCsvPath = QtWidgets.QTextEdit(self.centralwidget)
        self.textCsvPath.setGeometry(QtCore.QRect(30, 90, 621, 31))
        self.textCsvPath.setObjectName("textCsvPath")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 510, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.textVariavelAlvo = QtWidgets.QTextEdit(self.centralwidget)
        self.textVariavelAlvo.setGeometry(QtCore.QRect(30, 210, 231, 31))
        self.textVariavelAlvo.setObjectName("textVariavelAlvo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 271, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 271, 18))
        self.label_2.setObjectName("label_2")
        self.textResultado = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textResultado.setGeometry(QtCore.QRect(30, 290, 741, 161))
        self.textResultado.setObjectName("textResultado")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 271, 18))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 460, 741, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuSair = QtWidgets.QMenu(self.menubar)
        self.menuSair.setObjectName("menuSair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuSair.addAction(self.actionSair)
        self.menubar.addAction(self.menuSair.menuAction())

        self.retranslateUi(MainWindow)
        self.actionSair.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pensy Analytics APP"))
        self.buttonCsv.setText(_translate("MainWindow", "Selecionar CSV"))
        self.pushButton.setText(_translate("MainWindow", "Processar"))
        self.label.setText(_translate("MainWindow", "Selecione os dados de treinamento:"))
        self.label_2.setText(_translate("MainWindow", "Defina a variável alvo"))
        self.label_3.setText(_translate("MainWindow", "Resultado:"))
        self.menuSair.setTitle(_translate("MainWindow", "Configurações"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
